name: JW_Piano
version: ${project.version}
main: jw.piano.spigot.Main
api-version: 1.17
permissions:
  # plugin
  piano:
    description: Default permission for plugin
    children:
      - commands
      - gui
      - piano.create
      - piano.remove
      - piano.volume
      - piano.rename
      - piano.skin
      - piano.active
      - piano.effects
      - piano.pedal
      - piano.bench
      - piano.teleport
      - piano.detect-key
      - piano.desktop-client
      - piano.show-gui-hitbox

  piano.create:
    description: player can create piano

  piano.remove:
    description: player can remove piano

  piano.volume:
    description: player can edit piano volume in GUI

  piano.rename:
    description: player can rename piano in GUI

  piano.skin:
    description: player change piano skin in GUI

  piano.active:
    description: player change piano state in GUI

  piano.effects:
    description: player set piano particles in GUI

  piano.pedal:
    description: player enable/disable piano pedal in GUI

  piano.bench:
    description: player enable/disable piano bench in GUI

  piano.teleport:
    description: player teleport to piano in GUI

  piano.detect-key:
    description: player is able to click at the piano keys

  piano.desktop-client:
    description: player can use desktop-client

  piano.show-gui-hitbox:
    description: player can disable or enable gui hitbox

  # commands
  commands:
    description: Default permission for commands
    children:
      - piano.commands.lang
      - piano.commands.update
      - piano.commands.piano

  piano.commands.lang:
    description: Allow player to change plugin language
    default: op

  piano.commands.update:
    description: players with this permission can update plugin
    default: op

  piano.commands.piano:
    description: player open gui to create/remove piano

  # gui
  gui:
    description: Default permission for gui
