name: JW_Piano
version: ${project.version}
main: jw.piano.spigot.Main
api-version: 1.17
permissions:

  # plugin
  piano:
    description: Default permission for plugin
    children:
      - commands
      - gui
      - piano.create
      - piano.remove
      - piano.volume
      - piano.rename
      - piano.skin
      - piano.active
      - piano.sound
      - piano.effects
      - piano.pedal
      - piano.bench
      - piano.bench.active
      - piano.teleport
      - piano.detect-key
      - piano.desktop-client
      - midi-player

  piano.create:
    description: player can create piano

  piano.remove:
    description: player can remove piano

  piano.volume:
    description: player can edit piano volume in GUI

  piano.rename:
    description: player can rename piano in GUI

  piano.skin:
    description: player change piano skin in GUI

  piano.active:
    description: player change piano state in GUI

  piano.sound:
    description: player can change piano sound

  piano.effects:
    description: player set piano particles in GUI

  piano.pedal:
    description: player enable/disable piano pedal in GUI

  piano.bench:
    description: open bench GUI

  piano.bench.active:
    description: change visibility of bench

  piano.teleport:
    description: player teleport to piano in GUI

  piano.detect-key:
    description: player is able to click at the piano keys

  piano.desktop-client:
    description: player can use desktop-client

  # commands
  commands:
    description: Default permission for commands
    children:
      - piano.commands.lang
      - piano.commands.update
      - piano.commands.piano

  piano.commands.lang:
    description: Allow player to change plugin language
    default: op

  piano.commands.update:
    description: players with this permission can update plugin
    default: op

  piano.commands.piano:
    description: player open gui to create/remove piano

  # gui
  gui:
    description: Default permission for gui

  midi-player:
    description: opens midi player in gui
    children:
      - midi-player.play
      - midi-player.song
      - midi-player.type
      - midi-player.speed

  midi-player.play:
    description: can play/stop songs

  midi-player.song:
    description: can set current song, load song, delete song, skip

  midi-player.type:
    description: change midi player type

  midi-player.speed:
    description: change speed of midi song
