name: JW_Piano
version: ${project.version}
main: jw.piano.spigot.PianoPluginMain
author: JW
description: Basically It adds pianos and MIDI player to Minecraft
api-version: 1.17
#====================================================================================================
#                                                   Permissions
#====================================================================================================
permissions:

  # ======================================== jw-piano =================================
  jw-piano.*:
    description: full access

  # ======================================== jw-piano.piano ===========================
  jw-piano.piano.*:
    description: full access

  # ======================================== jw-piano.piano.keyboard ==================
  jw-piano.piano.keyboard.*:
    description: full access

  jw-piano.piano.keyboard.use:
    description: player click on the piano keys

  # ======================================== jw-piano.piano.bench =====================
  jw-piano.piano.bench.*:
    description: full access

  jw-piano.piano.bench.use:
    description: player sit on the bench

  # ======================================== jw-piano.piano.pedal =====================
  jw-piano.piano.pedal.*:
    description: full access

  jw-piano.piano.pedal.use:
    description: player can push sustain pedal with 'f' press

  # ======================================== jw-piano.commands ========================
  jw-piano.commands.*:
    description: full access

  jw-piano.commands.piano:
    description: player can open piano list gui

  jw-piano.commands.lang:
    description: Allow player to change plugin language

  jw-piano.commands.update:
    description: players with this permission can update plugin

  # ======================================== jw-piano.gui =============================
  jw-piano.gui.*:
    description: full access

  # ======================================== jw-piano.gui.midi-player =================
  jw-piano.gui.midi-player.*:
    description: full access

  jw-piano.gui.midi-player.speed:
    description: player can change speed of midi player

  jw-piano.gui.midi-player.player-type:
    description: MIDI player type

  jw-piano.gui.midi-player.next-song:
    description: player can play next song

  jw-piano.gui.midi-player.previous-song:
    description: player can play previous song

  jw-piano.gui.midi-player.play-stop:
    description: player can play or stop midi player

  jw-piano.gui.midi-player.select-song:
    description: player can add song to MIDI player

  jw-piano.gui.midi-player.remove-song:
    description: player can remove song from MIDI player

  # ======================================== jw-piano.gui.bench =======================
  jw-piano.gui.bench.*:
    description: full access

  jw-piano.gui.bench.move:
    description: player can move bench around

  # ======================================== jw-piano.gui.bench.settings ==============
  jw-piano.gui.bench.settings.*:
    description: full access

  jw-piano.gui.bench.settings.active:
    description: player can disable bench

  # ======================================== jw-piano.gui.piano =======================
  jw-piano.gui.piano.*:
    description: full access

  jw-piano.gui.piano.generate-token:
    description: player can generate token for desktop app

  jw-piano.gui.piano.volume:
    description: player can teleport to piano

  jw-piano.gui.piano.rename:
    description: player can rename piano

  jw-piano.gui.piano.teleport:
    description: player can teleport to piano

  jw-piano.gui.piano.skin:
    description: player can change piano skin

  jw-piano.gui.piano.effect:
    description: player can change piano particle effect

  jw-piano.gui.piano.sound:
    description: player can change piano sound

  jw-piano.gui.piano.clear:
    description: player can refresh piano model

  # ======================================== jw-piano.gui.piano.settings ==============
  jw-piano.gui.piano.settings.*:
    description: full access

  jw-piano.gui.piano.settings.piano-active:
    description: piano can be disabled but not removed

  jw-piano.gui.piano.settings.keyboard-pressing-active:
    description: player can enable/disable clicking at the piano keys

  jw-piano.gui.piano.settings.pedal-pressing-active:
    description: player can enable/disable pushing sustain pedal after 'f' press

  jw-piano.gui.piano.settings.desktop-app-active:
    description: piano will receiving data from desktop-app

  jw-piano.gui.piano.settings.pianist-active:
    description: pianist will appear and start playing

  # ======================================== jw-piano.gui.piano-list ==================
  jw-piano.gui.piano-list.*:
    description: full access

  jw-piano.gui.piano-list.create:
    description: player can create piano

  jw-piano.gui.piano-list.remove:
    description: player can remove piano





