#Generated template for Oraxen, It only contains models from pianopack
#Remember to refresh config when pianopack got updated
#Note that when you change LEATHER_HORSE_ARMOR to other material functionalities as Colored keys, Pianos, will not work

bench:
 displayname: bench
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/bench
  custom_model_data: 167072

flyingnote:
 displayname: flyingnote
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/flyingnote
  custom_model_data: 167073

icon:
 displayname: icon
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/icons/icon
  custom_model_data: 167074

piano-black-key:
 displayname: piano black key
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/key/piano_black_key
  custom_model_data: 167075

piano-black-key-down:
 displayname: piano black key down
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/key/piano_black_key_down
  custom_model_data: 167076

piano-key:
 displayname: piano key
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/key/piano_key
  custom_model_data: 167077

piano-key-down:
 displayname: piano key down
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/key/piano_key_down
  custom_model_data: 167078

piano-pedal:
 displayname: piano pedal
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/pedal/piano_pedal
  custom_model_data: 167079

piano-pedal-down:
 displayname: piano pedal down
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/pedal/piano_pedal_down
  custom_model_data: 167080

pianist-body:
 displayname: pianist body
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/pianist/pianist_body
  custom_model_data: 167081

pianist-hands:
 displayname: pianist hands
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/pianist/pianist_hands
  custom_model_data: 167082

pianist-head:
 displayname: pianist head
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/pianist/pianist_head
  custom_model_data: 167083

electric-piano:
 displayname: electric piano
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/piano/electric_piano
  custom_model_data: 167084

grand-piano:
 displayname: grand piano
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/piano/grand_piano
  custom_model_data: 167085

grand-piano-close:
 displayname: grand piano close
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/piano/grand_piano_close
  custom_model_data: 167086

up-right-piano-close:
 displayname: up right piano close
 material: LEATHER_HORSE_ARMOR
 excludeFromInventory: true
 Pack:
  generate_model: false
  model: item/jw/piano/up_right_piano_close
  custom_model_data: 167087


note_a:
  texture: icons/notes/a
  ascent: 2
  height: 2
  code: 4096
note_aSharp:
  texture: icons/notes/a_sharp
  ascent: 2
  height: 2
  code: 4097
note_b:
  texture: icons/notes/b
  ascent: 2
  height: 2
  code: 4098
note_c:
  texture: icons/notes/c
  ascent: 2
  height: 2
  code: 4099
note_cSharp:
  texture: icons/notes/c_sharp
  ascent: 2
  height: 2
  code: 4100
note_d:
  texture: icons/notes/d
  ascent: 2
  height: 2
  code: 4101
note_dSharp:
  texture: icons/notes/d_sharp
  ascent: 2
  height: 2
  code: 4102
note_e:
  texture: icons/notes/e
  ascent: 2
  height: 2
  code: 4103
note_f:
  texture: icons/notes/f
  ascent: 2
  height: 2
  code: 4104
note_fSharp:
  texture: icons/notes/f_sharp
  ascent: 2
  height: 2
  code: 4105
note_g:
  texture: icons/notes/g
  ascent: 2
  height: 2
  code: 4112
note_gSharp:
  texture: icons/notes/g_sharp
  ascent: 2
  height: 2
  code: 4113
  
